apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "eks-pod-identity-webhook-installer.name" . }}-manager
  namespace: {{ include "eks-pod-identity-webhook-installer.namespace" . }}
  labels:
    eks-pod-identity-webhook-installer.installer.h3poteto.dev: manager
spec:
  replicas: 1
  selector:
    matchLabels:
      eks-pod-identity-webhook-installer.installer.h3poteto.dev: manager
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        eks-pod-identity-webhook-installer.installer.h3poteto.dev: manager
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "eks-pod-identity-webhook-installer.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: manager
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          args:
            - /manager
            - --leader-elect
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
