{{- if .Values.rbac.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "eks-pod-identity-webhook-installer.serviceAccountName" . }}
  namespace: {{ include "eks-pod-identity-webhook-installer.namespace" . }}
  {{- with .Values.rbac.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
