{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-leader-election-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Release.Name }}-leader-election-role
subjects:
- kind: ServiceAccount
  name: {{ include "node-manager.serviceAccountName" . }}
  namespace: {{ include "node-manager.namespace" . }}
{{- end -}}
