apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fluentd-sidecar-injector.name" . }}-manager
  namespace: {{ include "fluentd-sidecar-injector.namespace" . }}
  labels:
    operator.h3poteto.dev: control-plane
spec:
  replicas: 1
  selector:
    matchLabels:
      operator.h3poteto.dev: control-plane
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        operator.h3poteto.dev: control-plane
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "fluentd-sidecar-injector.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: manager
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          args:
            - /fluentd-sidecar-injector
            - controller
            - sidecar-injector
          {{- if .Values.useCertManager }}
            - --use-cert-manager
          {{- end }}
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: WEBHOOK_CONTAINER_IMAGE
              value: "{{ .Values.image.repository}}:{{ .Values.image.tag }}"
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
